version: '2.4'

networks:
  backend:
    driver: "bridge"

services:
  neo:
    image: arramanenka/dumpster:healthy-neo
    environment:
      - NEO4J_AUTH=none
      - NEO4JLABS_PLUGINS=["graph-algorithms"]
      - NEO4J_dbms_security_procedures_unrestricted=algo\.\*
    ports:
      - '7687:7687'
      - '7474:7474'
    networks:
      - backend

  commute-range:
    build: ./
    environment:
      - SPRING_DATA_NEO4J_URI=bolt://neo:7687
    ports:
      - '8080:8080'
    restart: on-failure
    depends_on:
      neo:
        condition: service_healthy
    networks:
      - backend